//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation_MST
    {
        public Designation_MST()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public short id { get; set; }
        public string Designation { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
