//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Credits
    {
        public long id { get; set; }
        public long FromEmployee { get; set; }
        public long ToEmployee { get; set; }
        public short Credits { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsRedeemed { get; set; }
        public Nullable<System.DateTime> DateRedeemed { get; set; }
        public string Comments { get; set; }
    }
}
